# Generated by Django 3.2.10 on 2022-07-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurl',
            name='Rank',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
