# Generated by Django 3.2.10 on 2022-07-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20220716_1523'),
        ('RestApp', '0003_searchurl_rank'),
    ]

    operations = [
    ]
